<?php

/**
 * Webservice @ http://guesstimate.dbc.dk/~fvs/OpenLibrary/OpenHoldingStatus/trunk/server.php
 * */


/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function open_holdingstatus_ting_client_webservice() {
  $ret = array();
  $ret['holdingstatus']['class'] = 'open_holdingstatus';
  $ret['holdingstatus']['url'] = 'open_holdingstatus_url';
  return $ret;
}

/**
 * do a localisation request
 * */
function open_holdingstatus_localisationRequest($pid, $agencyId = 'DK-870970', $mergePids = FALSE, $outputType = 'json') {
  $client = new ting_client_class();
  $response = $client->do_holdingstatus(
    array(
      'action'         => 'localisationsRequest',
      'authentication' => FALSE,
      'agencyId'       => $agencyId,
      'pid'            => $pid,
      'mergePids'      => $mergePids,
      'outputType'     => $outputType,
      'callback'       => FALSE,
    )
  );

  if ( isset($response->error) ) {
    $error = $response->error->errorMessage->{'$'};
    drupal_set_message(t($error, array(), array('context' => 'open_holdingstatus')), 'error');
  }
  else {
    foreach ($response->localisationsResponse->localisations as $localisation) {
      if ( isset($localisation->pid) ) {
        if ( isset($localisation->pid->{'$'}) ) {
          $pid = $localisation->pid->{'$'};
        }
        else {
          $pid = $localisation->pid[0]->{'$'};
        }
      }
      if ( isset($localisation->errorMessage) ) {
        $localisations['error_message'][$pid] = $localisation->errorMessage->{'$'};
      }
      $agencies = ( isset($localisation->agency) ) ? $localisation->agency : array();
      foreach ($agencies as $agency) {
        $agencyId = $agency->agencyId->{'$'};
        $localisations['agencies'][$agencyId]['holdings'][$pid] = array(
          'localisationPid' => $agency->localisationPid->{'$'},
          'note' => ( isset($agency->note) ) ? $agency->note->{'$'} : '',
          'codes' => ( isset($agency->codes) ) ? $agency->codes->{'$'} : '',
          'callNumber' => ( isset($agency->callNumber) ) ? $agency->callNumber->{'$'} : '',
          'localIdentifier' => $agency->localIdentifier->{'$'},
        );
      }
    }
  }
  return $localisations;
}

/**
 * do a localisation request
 * */
function open_holdingstatus_localisationRequest_old($pid, $agencyId = 'DK-870970', $mergePids = FALSE, $outputType = 'php') {

  $localisations = array();

  $client = new ting_client_class();
  $response = $client->do_holdingstatus(
    array(
      'action'         => 'localisationsRequest',
      'authentication' => FALSE,
      'agencyId'       => $agencyId,
      'pid'            => $pid,
      'mergePids'      => $mergePids,
      'outputType'     => $outputType,
      'callback'       => FALSE,
    )
  );

  $response = unserialize($response)->localisationsResponse->_value->localisations;

  if ( isset($response->error) ) {
    $error = $response->error->_value;
    drupal_set_message(t($error, array(), array('context' => 'open_holdingstatus')), 'error');
  }
  else {
    $agencyIds = array();
    foreach ($response as $localisation) {
      if ( isset($localisation->_value->pid) ) {
        if ( isset($localisation->_value->pid->_value) ) {
          $pid = $localisation->_value->pid->_value;
        }
        else {
          $pid = $localisation->_value->pid[0]->_value;
        }
      }
      if ( isset($localisation->_value->errorMessage) ) {
        if ( isset($localisation->_value->errorMessage->_value) ) {
          $localisations[$pid]['error_message'] = $localisation->_value->errorMessage->_value;
        }
      }
      $agencies = ( isset($localisation->_value->agency) ) ? $localisation->_value->agency : array();

      foreach ($agencies as $agency) {
        $agencyIds[] = $agency->_value->agencyId->_value;
        $localisations[$pid]['agencies'][] = array(
          'localisationPid' => $agency->_value->localisationPid->_value,
          'agencyId' => $agency->_value->agencyId->_value,
          'note' => ( isset($agency->_value->note) ) ? $agency->_value->note->_value : '',
          'codes' => ( isset($agency->_value->codes) ) ? $agency->_value->codes->_value : '',
          'callNumber' => ( isset($agency->_value->callNumber) ) ? $agency->_value->callNumber->_value : '',
          'localIdentifier' => $agency->_value->localIdentifier->_value,
        );
      }
    }
  }
  return $localisations;
}

function open_holdingstatus_holdingsRequest (array $agency_ids, $pid, $outputType = 'json'){
  $client = new ting_client_class();

  foreach($agency_ids as $agency_id){
    $lookupRecord[] = array(
      'responderId' => $agency_id,
      'pid' => $pid,
    );
  }
  $request = array(
    'action'         => 'holdingsRequest',
    'authentication' => FALSE,
    'lookupRecord'       => $lookupRecord,
    'outputType'     => $outputType,
    'callback'       => FALSE,
  );
  $response = $client->do_holdingstatus($request);
  // TODO : Error handling
  return $response->holdingsResponse->responder;
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add a field to webservice client settings
 * @url to borchk
 * */
function open_holdingstatus_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['ting']['open_holdingstatus_url'] = array(
    '#type' => 'textfield',
    '#title' => t('OpenHoldingStatus URL'),
    '#description' => t('URL to OpenHoldingStatus e.g.: http://openholdingstatus.addi.dk/1.0/'),
    '#required' => TRUE,
    '#default_value' => variable_get('open_holdingstatus_url', FALSE),
  );
}

/**
 * Implements hook_how_r_u()
 * @return Array
 */
function open_holdingstatus_how_r_u() {
  return array('Holdingstatus' => variable_get('open_holdingstatus_url'));
}


/**
 * Error codes
 */
t('service_unavailable', array(), array('context' => 'open_holdingstatus'));
t('error_in_request', array(), array('context' => 'open_holdingstatus'));
t('service_not_supported_by_library', array(), array('context' => 'open_holdingstatus'));
t('cannot_parse_library_answer', array(), array('context' => 'open_holdingstatus'));
t('item_not_found', array(), array('context' => 'open_holdingstatus'));
t('error_searching_library', array(), array('context' => 'open_holdingstatus'));
t('error_fetching_request_order', array(), array('context' => 'open_holdingstatus'));
t('no_holding_return_from_library', array(), array('context' => 'open_holdingstatus'));
t('no_holdings_specified_by_library', array(), array('context' => 'open_holdingstatus'));
t('authentication_error', array(), array('context' => 'open_holdingstatus'));
t('agency_not_found', array(), array('context' => 'open_holdingstatus'));
t('no_agencies_found', array(), array('context' => 'open_holdingstatus'));

