<?php

/**
 * Webservice @ http://guesstimate.dbc.dk/~fvs/OpenLibrary/OpenHoldingStatus/trunk/server.php
 * */

define('DEFAULT_AGENCYID', 'DK-190101');
 
/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function open_holdingstatus_ting_client_webservice() {
  $ret = array();
  $ret['holdingstatus']['class']   = 'openHoldingsStatus';
  $ret['holdingstatus']['url']     = 'open_holdingstatus_url';
  $ret['holdingstatus']['xsd_url'] = 'open_holdingstatus_xsd_url';
  return $ret;
}

/**
 * Get localisations
 * @param array $pid
 * @param string $agency_id
 * */
function open_holdingstatus_localisationRequest($pid, $agencyId = FALSE) {
  if (!$agencyId) {
    $agencyId = variable_get('open_holdingstatus_agency_id', DEFAULT_AGENCYID);
  }
  $mergePids = FALSE;
  $outputType = 'json';

  $response = _open_holdingstatus_client_localisationsRequest($pid, $agencyId, $mergePids, $outputType);

  $localisations = _open_holdingstatus_parse_localisationsRequest($response);

  return $localisations;
}


/**
 * Do localisation request
 * @param array $pid
 * @param string $agency_id
 * @param boolean $mergePids
 * @param string $outputType
 * @return array
 */
function _open_holdingstatus_client_localisationsRequest($pid, $agencyId, $mergePids, $outputType) {

  $params = array(
    'action'         => 'localisationsRequest',
    'authentication' => FALSE,
    'agencyId'       => $agencyId,
    'pid'            => $pid,
    'mergePids'      => $mergePids,
    'outputType'     => $outputType,
    'callback'       => FALSE,
  );

  if (!class_exists('TingClient') && module_exists('libraries')) {
    libraries_load('TingClient');
  }

  $client = new ting_client_class();
  $response = $client->do_request(
    'holdingstatus',
    $params
  );
  return $response;
}


/**
 * Parse a localisation request
 * @param array $response
 * @return array
 */
function _open_holdingstatus_parse_localisationsRequest($response) {
  // ting_client returns false if something goes wrong
  if($response === FALSE){
    return FALSE;
  }

  $localisations = array();

  if ( isset($response->error) ) {
    $error = $response->error->errorMessage->{'$'};
    drupal_set_message(t($error, array(), array('context' => 'open_holdingstatus')), 'error');
  }
  else {
    if (!isset($response->localisationsResponse->localisations)){
      return t("no localizations", array(), array('context' => 'open_holdingstatus'));
    }
    foreach ($response->localisationsResponse->localisations as $localisation) {
      if ( isset($localisation->pid) ) {
        if ( isset($localisation->pid->{'$'}) ) {
          $pid = $localisation->pid->{'$'};
        }
        else {
          $pid = $localisation->pid[0]->{'$'};
        }
      }
      if ( isset($localisation->errorMessage) ) {
        $localisations['error_message'][$pid] = $localisation->errorMessage->{'$'};
      }
      $agencies = ( isset($localisation->agency) ) ? $localisation->agency : array();
      foreach ($agencies as $agency) {
        $agencyId = $agency->agencyId->{'$'};
        $localisations['agencies'][$agencyId]['holdings'][$pid] = array(
          'localisationPid' => $agency->localisationPid->{'$'},
          'note' => ( isset($agency->note) ) ? $agency->note->{'$'} : '',
          'codes' => ( isset($agency->codes) ) ? $agency->codes->{'$'} : '',
          'callNumber' => ( isset($agency->callNumber) ) ? $agency->callNumber->{'$'} : '',
          'localIdentifier' => $agency->localIdentifier->{'$'},
        );
      }
    }
  }

  return $localisations;

}

/**
 * Do holdings_request
 * @param array $agency_ids
 * @param string $pid
 * @param string $outputType
 * @return array
 */
function open_holdingstatus_holdingsRequest ($agency_ids, $pid, $outputType = 'json') {

  $lookupRecord = array();

  foreach($agency_ids as $agency_id){
    $lookupRecord[] = array(
      'responderId' => $agency_id,
      'pid' => $pid,
    );
  }
  $request = array(
    'action'         => 'holdingsRequest',
    'authentication' => FALSE,
    'lookupRecord'   => $lookupRecord,
    'outputType'     => $outputType,
    'callback'       => FALSE,
  );

  if (!class_exists('TingClient') && module_exists('libraries')) {
    libraries_load('TingClient');
  }
  $client = new ting_client_class();
  $response = $client->do_request('holdingstatus', $request);
  return open_holdingstatus_parse_request_response($response);
}

/**
 * Parse result from openHolding webservicen
 * @param $response
 * @return array
 */
function open_holdingstatus_parse_request_response($response){
  $return = array();
  // correct responses and error responses are divided into two methods. But we want to combine these
  if (isset($response->holdingsResponse->responder))
    $return = array_merge($return, $response->holdingsResponse->responder);
  if (isset($response->holdingsResponse->error)){
    $return = array_merge($return, $response->holdingsResponse->error);
  }

  return $return;
}

  /**
   * Do detailed_holdings_request
   * @param array $agency_ids
   * @param string $pid
   * @param string $outputType
   * @return array
   */
  function open_holdingstatus_detailedHoldingsRequest ($agency_ids, $pid, $outputType = 'json') {

    $lookupRecord = array();

    foreach($agency_ids as $agency_id){
      $lookupRecord[] = array(
        'responderId' => $agency_id,
        'pid' => $pid,
      );
    }
    $request = array(
      'action'         => 'detailedHoldingsRequest',
      'authentication' => FALSE,
      'lookupRecord'   => $lookupRecord,
      'outputType'     => $outputType,
      'callback'       => FALSE,
    );

    if (!class_exists('TingClient') && module_exists('libraries')) {
      libraries_load('TingClient');
    }
    $client = new ting_client_class();
    $response = $client->do_request('holdingstatus', $request);
    return open_holdingstatus_parse_detailed_request_response($response);
  }

  /**
   * Parse result from openHolding detailed webservicen
   * @param $response
   * @return array
   */
  function open_holdingstatus_parse_detailed_request_response($response){

    $return = array();
    // correct responses and error responses are divided into two methods. But we want to combine these
    if (isset($response->detailedHoldingsResponse->responderDetailed))
      $return = array_merge($return, $response->detailedHoldingsResponse->responderDetailed);
    if (isset($response->detailedHoldingsResponse->error)){
      $return = array_merge($return, $response->detailedHoldingsResponse->error);
    }

    return $return;
  }

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add a field to webservice client settings
 * @url to borchk
 * */
function open_holdingstatus_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {

  // don't start by defining the fieldset as an array. This way other modules can extend the fieldset.
  $form['holdingstatus']['#type'] = 'fieldset';
  $form['holdingstatus']['#title'] = t('OpenHoldingStatus settings', array(), array('context' => 'open_holdingstatus'));
  $form['holdingstatus']['#description'] = t('Client for OpenHoldingStatus, a service that can be used for checking and presenting the availability of materials held by Danish libraries.', array(), array('context' => 'open_holdingstatus'));
  $form['holdingstatus']['#collapsible'] = TRUE;
  $form['holdingstatus']['#collapsed'] = TRUE;
  $form['holdingstatus']['#tree'] = FALSE;

  $form['holdingstatus']['open_holdingstatus_url'] = array(
    '#type' => 'textfield',
    '#title' => t('OpenHoldingStatus URL', array(), array('context' => 'open_holdingstatus')),
    '#description' => t('URL to OpenHoldingStatus e.g.: http://openholdingstatus.addi.dk/x.x/', array(), array('context' => 'open_holdingstatus')),
    '#required' => TRUE,
    '#default_value' => variable_get('open_holdingstatus_url', FALSE),
  );

  $form['holdingstatus']['open_holdingstatus_xsd_url'] = array(
    '#type' => 'textfield',
    '#title' => t('OpenHoldingStatus XSD URL', array(), array('context' => 'open_holdingstatus')),
    '#description' => t('URL to OpenHoldingStatus XSD e.g.: http://openholdingstatus.addi.dk/x.x/openholdingstatus.xsd', array(), array('context' => 'open_holdingstatus')),
    '#required' => FALSE,
    '#default_value' => variable_get('open_holdingstatus_xsd_url', FALSE),
  );

  $form['holdingstatus']['open_holdingstatus_agency_id'] = array(
    '#type' => 'textfield',
    '#title' => t('OpenHoldingStatus agencyId', array(), array('context' => 'open_holdingstatus')),
    '#description' => t(
      'Default agencyId for localisationsRequest (%agency_id). <br/>If user is logged in and has a favorite library, this is used. 
      Otherwise the default library id is used. Format: "DK-xxxxxx"',
      array('%agency_id' => variable_get('open_holdingstatus_agency_id', DEFAULT_AGENCYID)), 
      array('context' => 'open_holdingstatus')
    ),
    '#required' => FALSE,
    '#default_value' => variable_get('open_holdingstatus_agency_id', DEFAULT_AGENCYID),
  );

}

/**
 * Implements hook_how_r_u()
 * @return Array
 */
function open_holdingstatus_how_r_u() {
  return array('Holdingstatus' => variable_get('open_holdingstatus_url'));
}


