<?php

/**
 * @file
 * Webservice mockup of openHoldingstatus
 */
function open_holdingstatus_webservice_mockup_menu() {
  $items['open_holdingstatus_webservice'] = array(
    'page callback' => 'open_holdingstatus_webservice_mockup_request',
    'access callback' => 'open_holdingstatus_webservice_mockup_access',
  );
  $items['open_holdingstatus_webservice/test'] = array(
    'page callback' => 'open_holdingstatus_webservice_test',
    'access callback' => TRUE
  );

  return $items;
}

function open_holdingstatus_webservice_test() {
  return '
    <form name="test" action="open_holdingstatus_webservice" method="POST" target="_blank">
      <textarea name="xml"></textarea>
      <input type="submit" name="sub" value="submit"/>
    </form>';
}


/**
 * Faking the request and returns result.
 * If other requests are made than on pid[0] = 870970-basis:28542941 &&  pid[0] = 870970-basis:28794932 no holdings will be returned.
 * @return String json
 */
function open_holdingstatus_webservice_mockup_request() {
  if (isset($_POST['xml'])) {
    $data = rawurldecode($_POST['xml']);
  }
  else {
    $data = file_get_contents('php://input');
  }
  $path = drupal_get_path('module', 'open_holdingstatus_webservice_mockup');

  if( $data ) {
    $envelope = open_holdingstatus_webservice_mockup_parse_xml($data);
  }
  else {
    echo 'welcome to open_holdingstatus_webservice mockup';
    return;
  }

  $request = $envelope->Body->localisationsRequest;

  $holdings_ok = FALSE;

  $holdings_ok = ( $request->agencyId == 'DK-870970' &&
                   $request->pid[0]   == '870970-basis:28542941' &&
                   $request->pid[1]   == '870970-basis:28794932' );

  drupal_add_http_header('Content-Type', 'application/json');

  if ( $holdings_ok ) {
    $resp = file_get_contents($path.'/holdings_ok.json');
  }
  else {
    $resp = file_get_contents($path.'/holdings_none.json');
  }

  print $resp;

}

/**
 * Parsing the request into a xml object
 * @param type request from ting-client
 * @return \SimpleXMLElement
 */
function open_holdingstatus_webservice_mockup_parse_xml($soap){
  $pattern = "/:?SOAP-ENV:?/";
  $replace = '';
  $xml = preg_replace($pattern, $replace, $soap);

  $envelope = new SimpleXMLElement($xml);
  return $envelope;
}

function open_holdingstatus_webservice_mockup_access() {
  return TRUE;
}
