<?php

/**
 * @file
 * Webservice mockup of openHoldingstatus
 */
function open_holdingstatus_webservice_mockup_menu() {
  $items['open_holdingstatus_webservice'] = array(
    'page callback' => 'open_holdingstatus_webservice_mockup_request',
    'access callback' => 'open_holdingstatus_webservice_mockup_access',
  );
  $items['open_holdingstatus_webservice/test'] = array(
    'page callback' => 'open_holdingstatus_webservice_test',
    'access callback' => TRUE
  );

  $items['open_holdingstatus_webservice/disable'] = array(
    'page callback' => 'open_holdingstatus_webservice_disable',
    'access callback' => TRUE
  );
  $items['open_holdingstatus_webservice/xsd'] = array(
    'page callback' => 'open_holdingstatus_get_xsd',
    'access callback' => TRUE
  );

  return $items;
}




function open_holdingstatus_webservice_test() {
  return '
    <form name="test" action="open_holdingstatus_webservice" method="POST" target="_blank">
      <textarea name="xml"></textarea>
      <input type="submit" name="sub" value="submit"/>
    </form>';
}

/** Disable this module
 * 
 */
function open_holdingstatus_webservice_disable() {
  module_disable(array('open_holdingstatus_webservice_mockup'));
  exit;
}

function open_holdingstatus_get_xsd(){
  $path = drupal_get_path('module', 'open_holdingstatus_webservice_mockup');
  $file = file_get_contents($path.'/openholdingstatus.xsd');
  print $file;
  exit;
}

/**
 * Faking the request and returns result.
 * If other requests are made than on pid[0] = 870970-basis:28542941 &&  pid[0] = 870970-basis:28794932 no holdings will be returned.
 * @return String json
 */
function open_holdingstatus_webservice_mockup_request() {
  if (isset($_POST['xml'])) {
    $data = rawurldecode($_POST['xml']);
  }
  else {
    $data = file_get_contents('php://input');
  }

  if ($data) {
    $envelope = open_holdingstatus_webservice_mockup_parse_xml($data);
  }
  else {
    echo 'welcome to open_holdingstatus_webservice mockup';
    return;
  }
  if (isset($envelope->Body->localisationsRequest)) {
    $resp = open_holdingstatus_webservice_mockup_localisations_request($envelope->Body->localisationsRequest);
  }
  else if (isset($envelope->Body->holdingsRequest)) {
    $resp = open_holdingstatus_webservice_mockup_holdings_request($envelope->Body->holdingsRequest);
  }

  drupal_add_http_header('Content-Type', 'application/json');
  print $resp;
}

function open_holdingstatus_webservice_mockup_holdings_request($request) {
  $holdings_ok = FALSE;

  $path = drupal_get_path('module', 'open_holdingstatus_webservice_mockup');
  $agency_id = '870970';
  $pid = '870970-basis:28542941';
  $holdings_ok = ( $request->lookupRecord->responderId == $agency_id &&
      $request->lookupRecord->pid == $pid );

  $agency_id = '715700';
  $pid = '870970-basis:29317038';
  $holdings_yellow = ( $request->lookupRecord->responderId == $agency_id &&
      $request->lookupRecord->pid == $pid );

  $agency_id = '710100';
  $pid = '870970-basis:20262710';
  $holdings_check_local = ( $request->lookupRecord->responderId == $agency_id &&
      $request->lookupRecord->pid == $pid );

  $agency_id = '763000';
  $pid = '870970-basis:06343570';
  $holdings_is_home = ( $request->lookupRecord->responderId == $agency_id &&
      $request->lookupRecord->pid == $pid );

  $agency_id = '710100';
  $pid = '870970-basis:28542941';
  $holdings_favourite = ( $request->lookupRecord->responderId == $agency_id &&
      $request->lookupRecord->pid == $pid );

  $agency_id = 'DK-870970';
  $pid = '870970-basis:28542941';
  $holdings_status = ( $request->lookupRecord->responderId == $agency_id &&
      $request->lookupRecord->pid == $pid );

  if ($holdings_ok) {
    $resp = file_get_contents($path . '/holdings_service_not_supported.json');
    // $resp = file_get_contents($path.'/holdingstatus_ok.json');
  }
  elseif ($holdings_yellow) {
    //$resp = file_get_contents($path.'/holdings_none.json');
    $resp = file_get_contents($path . '/holdings_service_yellow_lamp.json');
  }
  elseif ($holdings_check_local) {
    $resp = file_get_contents($path . '/holdings_check_local.json');
  }
  elseif ($holdings_is_home) {
    $resp = file_get_contents($path . '/holdings_is_home.json');
  }
  elseif ($holdings_favourite) {
    $resp = file_get_contents($path . '/holdings_favourite.json');
  }
  elseif ($holdings_status) {
    $resp = file_get_contents($path . '/holdings_status.json');
  }
  else {
    $resp = file_get_contents($path . '/holdings_none.json');
  }

  return $resp;
}

function open_holdingstatus_webservice_mockup_localisations_request($request) {
  $holdings_ok = FALSE;
  $path = drupal_get_path('module', 'open_holdingstatus_webservice_mockup');

  $holdings_ok = ( $request->agencyId == 'DK-870970' &&
      $request->pid[0] == '870970-basis:28542941' &&
      $request->pid[1] == '870970-basis:28794932' );

  $favourite_holdings = ( $request->agencyId == '710101' &&
      $request->pid[0] == '870970-basis:28542941' &&
      $request->pid[1] == '870970-basis:28794932' );


  if ($holdings_ok || $favourite_holdings) {
    //$resp = file_get_contents($path.'/holdings_ok.json');
    $resp = file_get_contents($path . '/localizations.json');
  }
  else {
    $resp = file_get_contents($path . '/holdings_none.json');
  }

  return $resp;
}

/**
 * Parsing the request into a xml object
 * @param type request from ting-client
 * @return \SimpleXMLElement
 */
function open_holdingstatus_webservice_mockup_parse_xml($soap) {
  $pattern = "/:?SOAP-ENV:?/";
  $replace = '';
  $xml = preg_replace($pattern, $replace, $soap);

  $envelope = new SimpleXMLElement($xml);
  return $envelope;
}

function open_holdingstatus_webservice_mockup_access() {
  return TRUE;
}
